[package]
name = "gazami"
version = "0.1.0"
edition = "2021"

[dependencies]
uefi = { version = "0.16.0", features = ["exts"] }
uefi-services = "0.13.0"
bincode = { version = "2.0.0-rc.1", default-features = false, features = ["derive"] }